service: external-account-manager
runtime: nodejs20
env: standard
env_variables:
  DBHOST: "35.219.28.103"
  DBNAME: "external-account-manager"
  DBUSER: "nodeuser"
  DBPASSWORD: "RotiKeju98*"
  DBENGINE: "postgresql"
  APPLICATION_NAME : "External_Account_Manager"
  APPLICATION_TITLE : "External_Account_Manager"
  APPLICATION_PORT : "8080"
